
package registration;

/**
 *
 * @author CYNTHIA
 */
import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
public class Registration extends javax.swing.JFrame {
     private JTextField idField, nameField, genderField, addressField, contactField;

public Registration() {
        setTitle("Registration Form");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JPanel panel = new JPanel();
        add(panel);
        placeComponents(panel);

        setVisible(true);
    }

    private void placeComponents(JPanel panel) {
        panel.setLayout(null);

        JLabel idLabel = new JLabel("ID:");
        idLabel.setBounds(10, 20, 80, 25);
        panel.add(idLabel);

        idField = new JTextField(20);
        idField.setBounds(100, 20, 200, 25);
        panel.add(idField);

        JLabel nameLabel = new JLabel("Name:");
        nameLabel.setBounds(10, 50, 80, 25);
        panel.add(nameLabel);

        nameField = new JTextField(20);
        nameField.setBounds(100, 50, 200, 25);
        panel.add(nameField);

        JLabel genderLabel = new JLabel("Gender:");
        genderLabel.setBounds(10, 80, 80, 25);
        panel.add(genderLabel);

        genderField = new JTextField(20);
        genderField.setBounds(100, 80, 200, 25);
        panel.add(genderField);

        JLabel addressLabel = new JLabel("Address:");
        addressLabel.setBounds(10, 110, 80, 25);
        panel.add(addressLabel);

        addressField = new JTextField(20);
        addressField.setBounds(100, 110, 200, 25);
        panel.add(addressField);

        JLabel contactLabel = new JLabel("Contact:");
        contactLabel.setBounds(10, 140, 80, 25);
        panel.add(contactLabel);

        contactField = new JTextField(20);
        contactField.setBounds(100, 140, 200, 25);
        panel.add(contactField);

        JButton registerButton = new JButton("Register");
        registerButton.setBounds(10, 180, 100, 25);
        registerButton.addActionListener((ActionEvent e) -> {
            register();
        });
        panel.add(registerButton);

        JButton exitButton = new JButton("Exit");
        exitButton.setBounds(120, 180, 100, 25);
        exitButton.addActionListener((ActionEvent e) -> {
            System.exit(0);
        });
        panel.add(exitButton);
    }
    private void register() {
        String id = idField.getText();
        String name = nameField.getText();
        String gender = genderField.getText();
        String address = addressField.getText();
        String contact = contactField.getText();

        try {
            
            String url="jdbc:mysql://localhost:3306/zu?autoReconnect=true&usesSSL=false";
            String user="root";
            String password="";
            try (Connection con = DriverManager.getConnection(url,user,password)) {
                Statement stm = con.createStatement();
                String query = "INSERT INTO students (id, name, gender, address, contact) VALUES ('" + id + "', '" + name + "', '" + gender + "', '" + address + "', '" + contact + "')";
                int res=stm.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Registration Successful!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "INCORRECT: " + e.getMessage());
        }
    }

    public static void main(String[] args) {
         Registration registration = new Registration();
    }
}
       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.

public class Registration {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
    }
    
}
